import { Check, Copy } from 'lucide-react'
import Image from 'next/image'
import { useMemo, useRef, useState } from 'react'
import * as runtime from 'react/jsx-runtime'

// Custom Pre component with Copy Button
const Pre = ({ children, ...props }: any) => {
  const [copied, setCopied] = useState(false)
  const textInput = useRef<HTMLPreElement>(null)

  const onCopy = () => {
    setCopied(true)
    navigator.clipboard.writeText(textInput.current?.textContent || '')
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <div className='group relative'>
      <pre ref={textInput} {...props}>
        {children}
      </pre>
      <button
        aria-label='Copy code'
        type='button'
        className={`absolute top-2 right-2 h-8 w-8 cursor-pointer rounded-lg border border-white/10 bg-gray-950/50 p-2 text-gray-400 opacity-0 transition-all group-hover:opacity-100 hover:bg-emerald-500 hover:text-gray-950 ${
          copied ? 'border-emerald-500 text-emerald-500 opacity-100' : ''
        }`}
        onClick={onCopy}
      >
        {copied ? <Check size={16} /> : <Copy size={16} />}
      </button>
    </div>
  )
}

/**
 *
 * 1. GLOBAL COMPONENTS MAP
 * These components are automatically available in every MDX file.
 * You don't need to import them manually in your markdown.
 */
const sharedComponents = {
  // RULE: "Hijack" the standard HTML <img> tag and use Next.js <Image /> instead.
  // This makes standard Markdown ![]() syntax optimized for SEO automatically.
  img: (props: any) => (
    <Image width={1200} height={630} className='rounded-lg border' {...props} />
  ),
  // our custom Pre component to copy code block
  pre: Pre,
  // Add other components you use everywhere here:
  // Callout,
  // Card,
  Image,
}

/**
 * 2. THE PARSER ENGINE
 * This function takes the "code string" generated by Velite and
 * turns it into a real, runnable React component.
 */
const useMDXComponent = (code: string) => {
  // 'new Function' executes the string as code.
  // We pass the 'runtime' so the code knows how to create <div>, <h1>, etc.
  const Component = useMemo(() => {
    const fn = new Function('runtime', code)
    return fn({ ...runtime }).default
  }, [code])

  return Component
}

interface MDXProps {
  code: string
  components?: Record<string, React.ComponentType>
}

/**
 * 3. THE RENDERER COMPONENT
 * This is the component you actually use in your Next.js pages.
 */
export const MDXContent = ({ code, components }: MDXProps) => {
  // Convert the Velite string into a component
  const Component = useMDXComponent(code)

  // Render the component.
  // We merge sharedComponents (Global) with components (Passed via props).
  return <Component components={{ ...sharedComponents, ...components }} />
}
