import type { Metadata } from "next"
import { Inter, Calistoga } from "next/font/google"
import "./globals.css"
import { ShootingStars } from "@/components/ui/shotting-star"
import { StarsBackground } from "@/components/ui/star-background"
import { ThemeProvider } from "@/components/theme-provider"
import grainImage from "@/assets/images/grain.jpg"
import { Header } from "@/sections/Header"
const inter = Inter({ subsets: ["latin"], variable: "--font-sans" })
const calistoga = Calistoga({
  subsets: ["latin"],
  variable: "--font-serif",
  weight: "400",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${calistoga.variable} bg-gray-900 dark:bg-black font-sans text-white antialiased relative z-100`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Header />
          {children}

          {/* Star Effect */}
        </ThemeProvider>
        <div className="fixed inset-0 pointer-events-none">
          <div
            className="fixed inset-0 -z-100 opacity-5"
            style={{
              backgroundImage: `url(${grainImage.src})`,
            }}
          />
          <ShootingStars />
          <StarsBackground />
        </div>
      </body>
    </html>
  )
}
