import type { Metadata } from 'next'
import { Inter, Calistoga } from 'next/font/google'
import { ShootingStars } from '@/components/ui/shotting-star'
import { StarsBackground } from '@/components/ui/star-background'
import grainImage from '@/assets/images/grain.jpg'
import { Header } from '@/sections/Header'
const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })
const calistoga = Calistoga({
  subsets: ['latin'],
  variable: '--font-serif',
  weight: '400',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function PortfolioLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <div className=''>
      <Header />
      {children}
      <div className='pointer-events-none fixed inset-0'>
        <div
          className='fixed inset-0 opacity-5'
          style={{
            backgroundImage: `url(${grainImage.src})`,
          }}
        />

        <ShootingStars />
        <StarsBackground />
      </div>
    </div>
  )
}
